import { motion } from "framer-motion";
import { theme } from "@/config/theme";
import { CardSkeleton } from "@/shared/components/skeleton/CardSkeleton";
import type { AISummaryResponse } from "../types/reports.types";

const HIGHLIGHT_STYLES = {
  good: {
    bg: theme.colors.health.recovery.bg,
    border: theme.colors.health.recovery.border,
    dot: theme.colors.health.recovery.DEFAULT,
  },
  warning: {
    bg: theme.colors.health.warning.bg,
    border: theme.colors.health.warning.border,
    dot: theme.colors.health.warning.DEFAULT,
  },
  danger: {
    bg: theme.colors.health.danger.bg,
    border: theme.colors.health.danger.border,
    dot: theme.colors.health.danger.DEFAULT,
  },
  info: {
    bg: theme.colors.health.strain.bg,
    border: theme.colors.health.strain.border,
    dot: theme.colors.health.strain.DEFAULT,
  },
};

const GRADE_COLORS: Record<string, string> = {
  A: theme.colors.health.recovery.DEFAULT,
  B: theme.colors.health.recovery.DEFAULT,
  C: theme.colors.health.warning.DEFAULT,
  D: theme.colors.health.warning.DEFAULT,
  F: theme.colors.health.danger.DEFAULT,
};

interface AISummaryCardProps {
  data: AISummaryResponse | undefined;
  isLoading: boolean;
}

export function AISummaryCard({ data, isLoading }: AISummaryCardProps) {
  if (isLoading) return <CardSkeleton />;
  if (!data) return null;

  const gradeColor = GRADE_COLORS[data.grade] || theme.colors.text.muted;

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl overflow-hidden"
      style={{
        background: theme.colors.surface[2],
        border: `1px solid ${theme.colors.border[1]}`,
      }}
    >
      {/* Header */}
      <div
        className="flex items-center justify-between px-6 py-5"
        style={{
          borderBottom: `1px solid ${theme.colors.border[1]}`,
          background: theme.colors.accent.subtle,
        }}
      >
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center"
            style={{ background: theme.colors.accent.primary, boxShadow: theme.shadows.accent }}
          >
            <i className="fas fa-brain" style={{ color: theme.colors.bg.primary }} />
          </div>
          <div>
            <div
              className="font-black tracking-tight"
              style={{
                fontSize: theme.typography.sizes.h3,
                color: theme.colors.text.primary,
                letterSpacing: "-0.02em",
              }}
            >
              AI Health Summary
            </div>
            <div style={{ fontSize: theme.typography.sizes.xxs, color: theme.colors.text.subtle }}>
              Generated by MediCare AI
            </div>
          </div>
        </div>

        {/* Grade badge */}
        <div className="text-right">
          <div
            className="font-black leading-none"
            style={{
              fontSize: "3rem",
              color: gradeColor,
              letterSpacing: "-0.05em",
              textShadow: `0 0 20px ${gradeColor}40`,
            }}
          >
            {data.grade}
          </div>
          <div
            className="font-bold uppercase tracking-wider"
            style={{ fontSize: theme.typography.sizes.xxs, color: theme.colors.text.subtle }}
          >
            {data.score.toFixed(0)}/100
          </div>
        </div>
      </div>

      <div className="p-6">
        {/* Summary paragraph */}
        <p
          className="leading-relaxed mb-6"
          style={{
            fontSize: theme.typography.sizes.sm,
            color: theme.colors.text.muted,
            lineHeight: 1.8,
          }}
        >
          {data.summary}
        </p>

        {/* Score progress bar */}
        <div className="mb-6">
          <div className="flex justify-between items-center mb-2">
            <span
              className="font-bold uppercase tracking-widest"
              style={{ fontSize: theme.typography.sizes.xxs, color: theme.colors.text.subtle }}
            >
              Overall Health Score
            </span>
            <span className="font-black" style={{ fontSize: theme.typography.sizes.sm, color: gradeColor }}>
              {data.score.toFixed(0)}%
            </span>
          </div>
          <div className="h-2 rounded-full overflow-hidden" style={{ background: "rgba(255,255,255,0.06)" }}>
            <motion.div
              className="h-full rounded-full"
              initial={{ width: "0%" }}
              animate={{ width: `${data.score}%` }}
              transition={{ duration: 1, delay: 0.3, ease: [0.4, 0, 0.2, 1] }}
              style={{ background: gradeColor, boxShadow: `0 0 8px ${gradeColor}` }}
            />
          </div>
        </div>

        {/* Highlights */}
        {data.highlights.length > 0 && (
          <div className="mb-6">
            <div
              className="font-bold uppercase tracking-widest mb-3"
              style={{ fontSize: theme.typography.sizes.xxs, color: theme.colors.text.subtle }}
            >
              Key Findings
            </div>
            <div className="space-y-2">
              {data.highlights.map((h, i) => {
                const hType = h.type as keyof typeof HIGHLIGHT_STYLES;
                const style = HIGHLIGHT_STYLES[hType] || HIGHLIGHT_STYLES.info;
                return (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -6 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.07 }}
                    className="flex items-start gap-3 p-3 rounded-xl border"
                    style={{ background: style.bg, borderColor: style.border }}
                  >
                    <div
                      className="w-1.5 h-1.5 rounded-full flex-shrink-0 mt-1.5"
                      style={{ background: style.dot }}
                    />
                    <p style={{ fontSize: theme.typography.sizes.sm, color: theme.colors.text.muted, lineHeight: 1.5 }}>
                      {h.text}
                    </p>
                  </motion.div>
                );
              })}
            </div>
          </div>
        )}

        {/* Action items */}
        {data.action_items.length > 0 && (
          <div>
            <div
              className="font-bold uppercase tracking-widest mb-3"
              style={{ fontSize: theme.typography.sizes.xxs, color: theme.colors.text.subtle }}
            >
              Recommended Actions
            </div>
            <div className="space-y-2">
              {data.action_items.map((item, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: -4 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.3 + i * 0.06 }}
                  className="flex items-start gap-3 p-3 rounded-xl"
                  style={{
                    background: theme.colors.surface[3],
                    border: `1px solid ${theme.colors.border[1]}`,
                  }}
                >
                  <div
                    className="w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5"
                    style={{
                      background: theme.colors.accent.subtle,
                      border: `1px solid ${theme.colors.accent.border}`,
                    }}
                  >
                    <span className="font-black" style={{ fontSize: "0.55rem", color: theme.colors.accent.primary }}>
                      {i + 1}
                    </span>
                  </div>
                  <p style={{ fontSize: theme.typography.sizes.sm, color: theme.colors.text.muted, lineHeight: 1.5 }}>
                    {item}
                  </p>
                </motion.div>
              ))}
            </div>
          </div>
        )}
      </div>
    </motion.div>
  );
}
