/**
 * PreventiveIntelligenceEvaluation — Evaluates the accuracy and utility
 * of early preventive health warnings generated by the AI.
 */
import { useCallback } from "react";

export interface PreventiveEvaluation {
  warningId: string;
  condition: string;
  leadTimeDays: number;
  outcome: "true_positive" | "false_positive" | "prevented" | "unknown";
  clinicalUtility: "high" | "low" | "harmful";
}

export function usePreventiveIntelligenceEvaluation() {
  const evaluate = useCallback((evaluations: PreventiveEvaluation[]): { precision: number; preventedRate: number; utilityScore: number } => {
    if (evaluations.length === 0) return { precision: 0, preventedRate: 0, utilityScore: 0 };
    const tp = evaluations.filter(e => e.outcome === "true_positive").length;
    const fp = evaluations.filter(e => e.outcome === "false_positive").length;
    const prevented = evaluations.filter(e => e.outcome === "prevented").length;
    const highUtility = evaluations.filter(e => e.clinicalUtility === "high").length;
    const harmful = evaluations.filter(e => e.clinicalUtility === "harmful").length;
    return {
      precision: (tp + fp) > 0 ? (tp / (tp + fp)) * 100 : 0,
      preventedRate: (evaluations.length - evaluations.filter(e => e.outcome === "unknown").length) > 0 ? (prevented / (evaluations.length - evaluations.filter(e => e.outcome === "unknown").length)) * 100 : 0,
      utilityScore: Math.max(0, (highUtility - harmful * 5) / evaluations.length * 100),
    };
  }, []);

  return { evaluate };
}
