"""
health_intelligence/coaching/psychological_safety.py
───────────────────────────────────────────────
Emotional and psychological safety guardrails for
all user-facing health communications.

Ensures:
  - No fear-based language
  - No guilt-driven coaching
  - No catastrophizing
  - Burnout-safe alerting
  - Emotionally supportive framing
  - Adaptive notification pacing

Every message generated by the coaching system
passes through this safety layer.
"""

import logging
import re
from typing import Optional

log = logging.getLogger(__name__)

# Banned phrases and patterns
FEAR_PATTERNS = [
    r"\bdanger\b",
    r"\bdangerous\b",
    r"\bfatal\b",
    r"\bdie\b",
    r"\bdying\b",
    r"\bdeath\b",
    r"\bworse(?:n|ning)\b",
    r"\bserious(?:ly)? ill\b",
    r"\birreversible\b",
    r"\bpermanent damage\b",
    r"\bemergency\b",
    r"\bcritical condition\b",
    r"\bimminent\b",
    r"\blife.?threatening\b",
]

GUILT_PATTERNS = [
    r"\byou(?:'re| are) failing\b",
    r"\byou should have\b",
    r"\byou(?:'re| are) not doing enough\b",
    r"\byour fault\b",
    r"\byou neglected\b",
    r"\bdisappointing\b",
    r"\byou(?:'re| are) lazy\b",
    r"\binadequate\b",
    r"\bshame\b",
]

# Reframing dictionary: unsafe → safe
REFRAMES = {
    "your health is getting worse": "your wellness trend suggests room for improvement",
    "you are failing": "there's an opportunity to adjust your approach",
    "dangerously high": "elevated beyond your typical range",
    "critically low": "lower than your usual baseline",
    "you must": "you might consider",
    "you need to": "it could help to",
    "you should": "you might want to",
    "warning": "heads up",
    "alarming": "noteworthy",
    "deteriorating rapidly": "changing more than usual",
}


class PsychologicalSafetyLayer:
    """
    Ensures all coaching and alert messages are
    emotionally safe and non-threatening.
    """

    def __init__(self):
        self._fear_re = [re.compile(p, re.IGNORECASE) for p in FEAR_PATTERNS]
        self._guilt_re = [re.compile(p, re.IGNORECASE) for p in GUILT_PATTERNS]

    def sanitize_message(
        self,
        message: str,
        allow_clinical_terms: bool = False,
    ) -> str:
        """
        Sanitize a message to remove fear/guilt language.
        Returns the cleaned message.
        """
        sanitized = message

        # Apply reframes
        for unsafe, safe in REFRAMES.items():
            sanitized = sanitized.replace(unsafe, safe)
            # Case-insensitive replacement
            pattern = re.compile(re.escape(unsafe), re.IGNORECASE)
            sanitized = pattern.sub(safe, sanitized)

        # Remove fear patterns
        if not allow_clinical_terms:
            for pattern in self._fear_re:
                if pattern.search(sanitized):
                    # Replace the match with a softer term
                    sanitized = pattern.sub("notable change", sanitized)

        # Remove guilt patterns
        for pattern in self._guilt_re:
            if pattern.search(sanitized):
                sanitized = pattern.sub(
                    "an area you can focus on", sanitized,
                )

        return sanitized.strip()

    def check_safety(self, message: str) -> dict:
        """
        Check a message for safety violations.
        Returns analysis with any flagged issues.
        """
        issues: list[dict] = []

        for pattern in self._fear_re:
            match = pattern.search(message)
            if match:
                issues.append({
                    "type": "fear_language",
                    "matched": match.group(),
                    "position": match.start(),
                })

        for pattern in self._guilt_re:
            match = pattern.search(message)
            if match:
                issues.append({
                    "type": "guilt_language",
                    "matched": match.group(),
                    "position": match.start(),
                })

        return {
            "is_safe": len(issues) == 0,
            "issues": issues,
            "issue_count": len(issues),
        }

    def frame_positive(self, message: str) -> str:
        """
        Reframe a message with positive, empowering language.
        """
        # Add encouraging opener if message starts negatively
        lower = message.lower()
        if any(lower.startswith(w) for w in ("your", "you")):
            if any(neg in lower[:50] for neg in ("low", "poor", "bad", "declin")):
                message = "Here's something to keep in mind: " + message

        # Add empowering closer
        if not message.endswith("."):
            message += "."
        message += " Small, consistent steps make a real difference."

        return message

    def apply_notification_pacing(
        self,
        user_id: int,
        messages: list[str],
        max_messages: int = 3,
    ) -> list[str]:
        """
        Limit the number of coaching messages to prevent
        overwhelm. Keeps the most important ones.
        """
        if len(messages) <= max_messages:
            return messages
        # Keep first and last, sample from middle
        return [messages[0]] + messages[1:max_messages - 1] + [messages[-1]]
