"""
health_intelligence/models.py
───────────────────────────────────────────────
SQLAlchemy models for persistent longitudinal
health intelligence storage.

Tables:
  - health_baselines         — Personal physiological baselines
  - health_scores            — Time-series health score history
  - preventive_alerts        — Generated preventive alerts
  - health_events            — Life/health event timeline
  - symptom_logs             — Timestamped symptom entries
  - wearable_snapshots       — Raw wearable data snapshots
  - physiological_states     — Real-time inferred physiological states
  - live_sessions            — Continuous session lifecycle tracking

All tables are indexed on (user_id, recorded_at) for
efficient time-series querying.
"""

from sqlalchemy import (
    Column, Integer, String, Float,
    Boolean, DateTime, ForeignKey, Text, JSON,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from core.database import Base


# ── Personal Health Baselines ────────────────────────────────

class HealthBaselineLog(Base):
    """
    Snapshot of a user's calculated personal baselines.
    Recalculated periodically as new data arrives.
    """
    __tablename__ = "health_baselines"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Physiological baselines
    resting_hr_bpm = Column(Float, nullable=True)
    avg_spo2_percent = Column(Float, nullable=True)
    avg_sleep_hours = Column(Float, nullable=True)
    avg_steps = Column(Float, nullable=True)
    avg_stress_level = Column(Float, nullable=True)
    avg_active_minutes = Column(Float, nullable=True)
    avg_calories_burned = Column(Float, nullable=True)
    avg_systolic_bp = Column(Float, nullable=True)
    avg_diastolic_bp = Column(Float, nullable=True)
    avg_temperature_celsius = Column(Float, nullable=True)
    avg_respiratory_rate = Column(Float, nullable=True)
    avg_blood_glucose = Column(Float, nullable=True)

    # Standard deviations (for anomaly detection)
    std_hr_bpm = Column(Float, nullable=True)
    std_spo2_percent = Column(Float, nullable=True)
    std_sleep_hours = Column(Float, nullable=True)
    std_steps = Column(Float, nullable=True)
    std_stress_level = Column(Float, nullable=True)

    # Baseline metadata
    data_points_used = Column(Integer, default=0)
    window_days = Column(Integer, default=14)
    baseline_confidence = Column(
        Float, default=0.0,
        comment="0.0–1.0: how reliable this baseline is",
    )
    freshness_score = Column(
        Float, default=0.0,
        comment="0.0–1.0: how recent the underlying data is",
    )

    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    user = relationship("User", backref="health_baselines")


# ── Health Score History ─────────────────────────────────────

class HealthScoreLog(Base):
    """
    Time-series log of computed health scores.
    One entry per scoring computation.
    """
    __tablename__ = "health_scores"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Core scores (0–100)
    health_score = Column(Float, nullable=False, default=50.0)
    recovery_score = Column(Float, nullable=True)
    wellness_index = Column(Float, nullable=True)
    fatigue_score = Column(Float, nullable=True)
    cardiovascular_score = Column(Float, nullable=True)
    resilience_score = Column(Float, nullable=True)

    # Recovery modelling
    recovery_velocity = Column(
        Float, nullable=True,
        comment="Rate of recovery (higher = faster bounce-back)",
    )
    sleep_debt_hours = Column(Float, nullable=True)

    # Score metadata
    inputs_used = Column(
        JSON, nullable=True,
        comment="Which data sources contributed to this score",
    )
    freshness_score = Column(Float, default=0.0)
    score_confidence = Column(Float, default=0.0)

    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    user = relationship("User", backref="health_scores")


# ── Preventive Alerts ────────────────────────────────────────

class PreventiveAlertLog(Base):
    """
    History of preventive alerts generated by the
    intelligence engine.
    """
    __tablename__ = "preventive_alerts"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    alert_type = Column(
        String(50), nullable=False,
        comment="fatigue | burnout | sleep_debt | trend_degradation | anomaly",
    )
    severity = Column(String(20), default="moderate")
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    contributing_factors = Column(JSON, nullable=True)
    confidence = Column(Float, default=0.0)
    is_acknowledged = Column(Boolean, default=False)

    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    user = relationship("User", backref="preventive_alerts")


# ── Health Event Timeline ────────────────────────────────────

class HealthEventLog(Base):
    """
    Timestamped life/health events for future
    event-health correlation analysis.

    Event types: illness, medication_change, travel,
    exam_stress, sleep_disruption, recovery_period, etc.
    """
    __tablename__ = "health_events"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    event_type = Column(
        String(50), nullable=False,
        comment=(
            "illness | medication_change | travel | exam_stress | "
            "sleep_disruption | recovery_period | lifestyle_change | other"
        ),
    )
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)
    severity = Column(String(20), nullable=True)
    metadata_json = Column(
        JSON, nullable=True,
        comment="Flexible extra data for the event",
    )

    started_at = Column(
        DateTime(timezone=True),
        nullable=False,
        comment="When the event began",
    )
    ended_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the event ended (null = ongoing)",
    )
    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    user = relationship("User", backref="health_events")


# ── Symptom Logs (persistent) ────────────────────────────────

class SymptomLogEntry(Base):
    """
    Persistent timestamped symptom entry for
    longitudinal symptom tracking and pattern mining.
    """
    __tablename__ = "symptom_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    symptom_name = Column(
        String(100), nullable=False,
        comment="Canonical snake_case symptom name",
    )
    severity_weight = Column(Integer, default=3)
    source = Column(
        String(30), default="user_input",
        comment="user_input | nlp_extraction | wearable_derived",
    )

    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    user = relationship("User", backref="symptom_logs")


# ── Wearable Snapshots (persistent) ─────────────────────────

class WearableSnapshot(Base):
    """
    Persistent wearable data snapshot for time-series
    analytics — one row per sync event.
    """
    __tablename__ = "wearable_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    heart_rate_bpm = Column(Float, nullable=True)
    spo2_percent = Column(Float, nullable=True)
    steps = Column(Integer, nullable=True)
    calories_burned = Column(Float, nullable=True)
    sleep_hours = Column(Float, nullable=True)
    active_minutes = Column(Integer, nullable=True)
    distance_km = Column(Float, nullable=True)
    stress_level = Column(Float, nullable=True)
    source = Column(String(30), default="unknown")

    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    user = relationship("User", backref="wearable_snapshots")


# ── Physiological State Logs (real-time) ─────────────────────

class PhysiologicalStateLog(Base):
    """
    Persists real-time inferred physiological states.

    State types: resting, active, stressed, recovering,
    sleeping, fatigued, abnormal, workout, unknown.

    Supports future digital physiology modelling and
    adaptive behavioral learning.
    """
    __tablename__ = "physiological_states"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    state = Column(
        String(30), nullable=False,
        comment=(
            "resting | active | stressed | recovering | "
            "sleeping | fatigued | abnormal | workout | unknown"
        ),
    )
    confidence = Column(
        Float, default=0.0,
        comment="0.0–1.0: inference confidence",
    )
    contributing_signals = Column(
        JSON, nullable=True,
        comment="Which signals drove this state inference",
    )
    context = Column(
        JSON, nullable=True,
        comment="Contextual metadata (circadian phase, activity, etc.)",
    )
    fusion_snapshot = Column(
        JSON, nullable=True,
        comment="Fused sensor values at time of inference",
    )

    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    user = relationship("User", backref="physiological_states")


# ── Live Session Logs ────────────────────────────────────────

class LiveSessionLog(Base):
    """
    Tracks continuous live sessions — workout, sleep,
    recovery, and stress episodes — with full lifecycle.

    Supports:
      - session state transitions
      - session-quality scoring
      - session summaries
    """
    __tablename__ = "live_sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    session_type = Column(
        String(30), nullable=False,
        comment="workout | sleep | recovery | stress | unknown",
    )
    status = Column(
        String(20), default="active",
        comment="active | paused | completed | abandoned",
    )
    quality_score = Column(
        Float, nullable=True,
        comment="0–100 session quality computed at end",
    )
    summary = Column(
        JSON, nullable=True,
        comment="Session summary with key metrics",
    )
    state_transitions = Column(
        JSON, nullable=True,
        comment="List of state transitions during session",
    )
    metadata_json = Column(
        JSON, nullable=True,
        comment="Flexible extra data",
    )

    started_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    ended_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Null while session is active",
    )
    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    user = relationship("User", backref="live_sessions")
